//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string DuongDanHinhAnh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int IdDanhMucSanPham { get; set; }
        public bool HienThi { get; set; }
        public bool Hot { get; set; }
        public bool NoiBat { get; set; }
        public bool KhuyenMai { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
    }
}
